# Generated by Django 3.2.19 on 2023-07-02 16:29

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('category', models.CharField(choices=[('ST', 'Starters'), ('PI', 'Pizza'), ('PA', 'Pasta')], default='ST', max_length=2)),
                ('image', cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/dpwp5cavi/image/upload/v1687277051/menu_pic_q2kjau.jpg', max_length=255, verbose_name='image')),
            ],
        ),
    ]
